import { useCallback, useMemo, useRef } from 'react'

/**
 * Keeps the horizontal scroll position of several staff canvases in lock-step so
 * that, with system-wide aligned measure widths, barlines stay vertically aligned
 * across all staves. Each canvas registers its scroll container and reports scroll
 * events; siblings are updated to match. Also exposes `scrollAllTo` for the
 * auto-center behaviour to drive every staff at once.
 */
export interface ScrollSync {
  register: (el: HTMLDivElement | null) => void
  onScroll: (el: HTMLDivElement) => void
  scrollAllTo: (left: number, smooth?: boolean) => void
}

export function useScrollSync(): ScrollSync {
  const containers = useRef<Set<HTMLDivElement>>(new Set())
  const syncing = useRef(false)
  const suppressUntil = useRef(0)

  const register = useCallback((el: HTMLDivElement | null) => {
    // We can't reliably know when an element unmounts here, so prune detached
    // nodes lazily on each sync rather than tracking removals.
    if (el) containers.current.add(el)
  }, [])

  const apply = useCallback((left: number, source?: HTMLDivElement) => {
    if (syncing.current) return
    syncing.current = true
    for (const el of containers.current) {
      if (!el.isConnected) { containers.current.delete(el); continue }
      if (el === source) continue
      if (el.scrollLeft !== left) el.scrollLeft = left
    }
    // Release on the next frame so the programmatic scrolls we just triggered
    // don't bounce back through their own scroll handlers.
    requestAnimationFrame(() => { syncing.current = false })
  }, [])

  const onScroll = useCallback((el: HTMLDivElement) => {
    // Ignore the stream of scroll events generated by a smooth programmatic scroll.
    if (performance.now() < suppressUntil.current) return
    apply(el.scrollLeft, el)
  }, [apply])

  const scrollAllTo = useCallback((left: number, smooth = false) => {
    if (smooth) {
      // Animate every container to the same target; suppress the resulting scroll
      // events so siblings don't fight each other mid-animation.
      suppressUntil.current = performance.now() + 600
      for (const el of containers.current) {
        if (!el.isConnected) { containers.current.delete(el); continue }
        el.scrollTo({ left, behavior: 'smooth' })
      }
      return
    }
    apply(left)
  }, [apply])

  // Stable object identity so consumers' ref callbacks/effects don't churn.
  return useMemo(() => ({ register, onScroll, scrollAllTo }), [register, onScroll, scrollAllTo])
}
